export const myProjects = [
  {
    title: "mock-up Portfolio",
    subtitle:
      "mock up portfolio task from front-end-mentor but I used my own picture and name",
    category: ["bootstrap"],
    img: "./projects/1.png",
    link: "https://mano4life.github.io/mockup-Portfolio/",
    github: "https://github.com/Mano4life/mockup-Portfolio",
  },
  {
    title: "Fylo landing page",
    subtitle: "task from front-end-mentor made with bootstrap",
    category: ["bootstrap"],
    img: "./projects/2.png",
    link: "https://mano4life.github.io/FEM-fylo-darkTheme-LP/",
    github: "https://github.com/Mano4life/FEM-fylo-darkTheme-LP",
  },
  {
    title: "music player",
    subtitle:
      "music player features a working media buttons and soon a playlist",
    category: ["vanilla"],
    img: "./projects/3.png",
    link: "https://mano4life.github.io/30-days-JS/no7_MusicPlayer/",
    github: "https://github.com/Mano4life/30-days-JS/tree/main/no7_MusicPlayer",
  },
  {
    title: "form sign up / in",
    subtitle: "animated sign up/in form with a modern look",
    category: ["vanilla"],
    img: "./projects/4.png",
    link: "https://mano4life.github.io/sign-inup-form/",
    github: "https://github.com/Mano4life/sign-inup-form",
  },
  {
    title: "PS store landing page",
    subtitle: "simple responsive landing page for a ps store",
    category: ["vanilla"],
    img: "./projects/5.png",
    link: "https://mano4life.github.io/PS-landingPage/PS-landingP",
    github: "https://github.com/Mano4life/PS-landingPage",
  },
  {
    title: "pricing toggle",
    subtitle: "task from front-end-mentor made responsive with bootstrap",
    category: ["bootstrap"],
    img: "./projects/6.png",
    link: "https://mano4life.github.io/fem-pricing-component-withToggle/",
    github: "https://github.com/Mano4life/fem-pricing-component-withToggle",
  },
  {
    title: "quote generator",
    subtitle:
      "quote generator which feature a post button that instantly directs to twitter",
    category: ["vanilla"],
    img: "./projects/7.png",
    link: "https://mano4life.github.io/30-days-JS/no4_QuoteCreator/",
    github:
      "https://github.com/Mano4life/30-days-JS/tree/main/no4_QuoteCreator",
  },
  {
    title: "quiz form",
    subtitle: "a quiz form with grading score",
    category: ["vanilla"],
    img: "./projects/8.png",
    link: "https://mano4life.github.io/30-days-JS/no2_QuizApp/",
    github: "https://github.com/Mano4life/30-days-JS/tree/main/no2_QuizApp",
  },
  {
    title: "QR generator",
    subtitle: "a fully functional QR generator",
    category: ["vanilla"],
    img: "./projects/9.png",
    link: "https://mano4life.github.io/30-days-JS/no5_QRgenerator/",
    github: "https://github.com/Mano4life/30-days-JS/tree/main/no5_QRgenerator",
  },
  {
    title: "React Portfolio",
    subtitle: "my first React Portfolio",
    category: ["react"],
    img: "./projects/10.png",
    link: "https://mano4life.github.io/portfolio/",
    github: "https://github.com/Mano4life/portfolio",
  },
];
